cluster.name: "es-cluster"
network.host: 192.168.3.1
http.port: 9200
# 开启es跨域
http.cors.enabled: true
http.cors.allow-origin: "*"
# 为elasticsearch-head 开启认证
http.cors.allow-headers: Authorization,X-Requested-With,Content-Type,Content-Length
# 开启安全控制
xpack.security.enabled: true
xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.verification_mode: certificate
xpack.security.transport.ssl.keystore.path: ./certs/elastic-certificates.p12
xpack.security.transport.ssl.truststore.path: ./certs/elastic-certificates.p12
